#ifndef WA824I_LEXER_ERR_H_
#define WA824I_LEXER_ERR_H_

enum LEXER_ERR_ {
	LEXER_ERR_INTERNAL,
	LEXER_ERR_INVAL_PARAM,
	LEXER_ERR_INVAL_SYNTAX,
	LEXER_ERR_INVAL_LEXEME_LEN,
	LEXER_ERR_INVAL_LINE_LEN,
	LEXER_ERR_INVAL_CHAR,
	LEXER_ERR_INVAL_ASCII,	/* '<ascii>' form.  ex) 'A', 'B' */
	LEXER_ERR_INVAL_STRING,
	LEXER_ERR_INVAL_INTEGER,
};



#endif
